FROM dokken/debian-9

USER root

LABEL maintainer="Armindo Cachada <armindo.cachada@spltech.co.uk>"
RUN echo "deb http://ftp.debian.org/debian stretch-backports main" | sudo tee /etc/apt/sources.list.d/backports.list


RUN apt-get update
RUN apt install -t stretch-backports npm nodejs -y
RUN apt-get install -y openvpn apache2 php-mysql mysql-server php-zip php unzip git wget sed curl nano
RUN npm install -g bower

WORKDIR /root
RUN git clone https://github.com/zfrkrc/OpenVPN-Admin-feature-ldap.git
WORKDIR /root/OpenVPN-Admin
RUN cp -r "./installation/scripts" "/etc/openvpn/" && chmod +x "/etc/openvpn/scripts/"* && \
    cp "./installation/server.conf" "/etc/openvpn/" && mkdir "/etc/openvpn/ccd"


# change group nogroup to group nobody
RUN sed -i "s/group nogroup/group nobody/" "/etc/openvpn/server.conf" && \
    sed -i "s/explicit-exit-notify 1/explicit-exit-notify 0/" "/etc/openvpn/server.conf"

# Get the rsa keys
WORKDIR /root/
RUN curl -L "https://github.com/OpenVPN/easy-rsa/releases/download/v3.1.2/EasyRSA-3.1.2.tgz" -O && \
    tar -xaf "EasyRSA-3.1.2.tgz" && mv "EasyRSA-3.1.2" /etc/openvpn/easy-rsa &&rm "EasyRSA-3.1.2.tgz"

COPY ./openvpn/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh


# Make ip forwading and make it persistent
RUN echo "net.ipv4.ip_forward = 1" >> "/etc/sysctl.conf"
RUN sed -i -e 's/\r$//' /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]
